# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageQueryUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ImageQuery(object):
    def setupUi(self, ImageQuery):
        ImageQuery.setObjectName("ImageQuery")
        ImageQuery.resize(700, 550)
        self.centralwidget = QtWidgets.QWidget(ImageQuery)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 50, 701, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(20, 200, 651, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_image_data = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_image_data.setGeometry(QtCore.QRect(20, 60, 481, 20))
        self.lineEdit_image_data.setObjectName("lineEdit_image_data")
        self.button_browse_image_data = QtWidgets.QPushButton(self.tab)
        self.button_browse_image_data.setGeometry(QtCore.QRect(510, 60, 41, 23))
        self.button_browse_image_data.setObjectName("button_browse_image_data")
        self.button_load_image_data = QtWidgets.QPushButton(self.tab)
        self.button_load_image_data.setGeometry(QtCore.QRect(560, 60, 111, 23))
        self.button_load_image_data.setObjectName("button_load_image_data")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.label_3.setObjectName("label_3")
        self.lineEdit_database = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_database.setGeometry(QtCore.QRect(20, 130, 481, 20))
        self.lineEdit_database.setObjectName("lineEdit_database")
        self.button_browse_database = QtWidgets.QPushButton(self.tab)
        self.button_browse_database.setGeometry(QtCore.QRect(510, 130, 41, 23))
        self.button_browse_database.setObjectName("button_browse_database")
        self.button_save_database = QtWidgets.QPushButton(self.tab)
        self.button_save_database.setGeometry(QtCore.QRect(560, 130, 51, 23))
        self.button_save_database.setObjectName("button_save_database")
        self.button_load_database = QtWidgets.QPushButton(self.tab)
        self.button_load_database.setGeometry(QtCore.QRect(620, 130, 51, 23))
        self.button_load_database.setObjectName("button_load_database")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 47, 13))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.button_back = QtWidgets.QPushButton(self.tab_2)
        self.button_back.setGeometry(QtCore.QRect(380, 40, 61, 31))
        self.button_back.setObjectName("button_back")
        self.button_next = QtWidgets.QPushButton(self.tab_2)
        self.button_next.setGeometry(QtCore.QRect(550, 40, 61, 31))
        self.button_next.setObjectName("button_next")
        self.resultView = QtWidgets.QGraphicsView(self.tab_2)
        self.resultView.setGeometry(QtCore.QRect(300, 80, 391, 391))
        self.resultView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.resultView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.resultView.setObjectName("resultView")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_4.setObjectName("label_4")
        self.lineEdit_image = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_image.setGeometry(QtCore.QRect(50, 10, 581, 20))
        self.lineEdit_image.setObjectName("lineEdit_image")
        self.button_browse_image = QtWidgets.QPushButton(self.tab_2)
        self.button_browse_image.setGeometry(QtCore.QRect(640, 10, 41, 23))
        self.button_browse_image.setObjectName("button_browse_image")
        self.button_query_image = QtWidgets.QPushButton(self.tab_2)
        self.button_query_image.setGeometry(QtCore.QRect(180, 70, 61, 31))
        self.button_query_image.setObjectName("button_query_image")
        self.queryView = QtWidgets.QGraphicsView(self.tab_2)
        self.queryView.setGeometry(QtCore.QRect(10, 190, 281, 281))
        self.queryView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.queryView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.queryView.setObjectName("queryView")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(20, 70, 21, 16))
        self.label_6.setObjectName("label_6")
        self.comboBox_bin_number = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_bin_number.setGeometry(QtCore.QRect(50, 70, 61, 22))
        self.comboBox_bin_number.setObjectName("comboBox_bin_number")
        self.button_result_histogram = QtWidgets.QPushButton(self.tab_2)
        self.button_result_histogram.setGeometry(QtCore.QRect(460, 40, 75, 31))
        self.button_result_histogram.setObjectName("button_result_histogram")
        self.button_query_histogram = QtWidgets.QPushButton(self.tab_2)
        self.button_query_histogram.setGeometry(QtCore.QRect(20, 160, 75, 23))
        self.button_query_histogram.setObjectName("button_query_histogram")
        self.slider_select_top = QtWidgets.QSlider(self.tab_2)
        self.slider_select_top.setGeometry(QtCore.QRect(80, 120, 161, 21))
        self.slider_select_top.setMaximum(100)
        self.slider_select_top.setSingleStep(5)
        self.slider_select_top.setProperty("value", 75)
        self.slider_select_top.setTracking(True)
        self.slider_select_top.setOrientation(QtCore.Qt.Horizontal)
        self.slider_select_top.setInvertedAppearance(False)
        self.slider_select_top.setInvertedControls(False)
        self.slider_select_top.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slider_select_top.setTickInterval(5)
        self.slider_select_top.setObjectName("slider_select_top")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(20, 120, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_select_top_value = QtWidgets.QLabel(self.tab_2)
        self.label_select_top_value.setGeometry(QtCore.QRect(260, 120, 21, 20))
        self.label_select_top_value.setObjectName("label_select_top_value")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        ImageQuery.setCentralWidget(self.centralwidget)

        self.retranslateUi(ImageQuery)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ImageQuery)

    def retranslateUi(self, ImageQuery):
        _translate = QtCore.QCoreApplication.translate
        ImageQuery.setWindowTitle(_translate("ImageQuery", "ImageQuery_OpenCV"))
        self.label.setText(_translate("ImageQuery", "Image Query"))
        self.label_2.setText(_translate("ImageQuery", "Image Data"))
        self.button_browse_image_data.setText(_translate("ImageQuery", "..."))
        self.button_load_image_data.setText(_translate("ImageQuery", "Load"))
        self.label_3.setText(_translate("ImageQuery", "Database"))
        self.button_browse_database.setText(_translate("ImageQuery", "..."))
        self.button_save_database.setText(_translate("ImageQuery", "Save"))
        self.button_load_database.setText(_translate("ImageQuery", "Load"))
        self.label_5.setText(_translate("ImageQuery", "Progress"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ImageQuery", "Data"))
        self.button_back.setText(_translate("ImageQuery", "Back"))
        self.button_next.setText(_translate("ImageQuery", "Next"))
        self.label_4.setText(_translate("ImageQuery", "Image:"))
        self.button_browse_image.setText(_translate("ImageQuery", "..."))
        self.button_query_image.setText(_translate("ImageQuery", "Query"))
        self.label_6.setText(_translate("ImageQuery", "Bin"))
        self.button_result_histogram.setText(_translate("ImageQuery", "Histogram"))
        self.button_query_histogram.setText(_translate("ImageQuery", "Histogram"))
        self.label_7.setText(_translate("ImageQuery", "Select top"))
        self.label_select_top_value.setText(_translate("ImageQuery", "75"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ImageQuery", "Query"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ImageQuery", "P(R)"))

